### PR TITLE
Fix: add the cross-env package to dependencies

### PR DESCRIPTION
**Pull request by timor-m**
##  add the cross-env package to dependencies

```
[√ ] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [√ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

_please describe the changes that you are making_

_for features, please describe how to use the new feature_

_please include a reference to an existing issue, if applicable_

## Does this PR introduce a breaking change?

```
[ ] Yes
[√ ] No
```

### CODE REVIEW

**Comment by timor-m** [comment]
@huan Can you review it for me when you have time?

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by timor-m** [comment]
@huan 
Thank you for your reply. 
The CLA has been completed, but the github actions test has not yet been completed.

**Comment by huan** [comment]
Hi @timor-m , I think the `cross-env` and `npm-run-all` will be installed even without the direct dependencies. Please correct me if I'm wrong.

This PR includes many unrelated changes, including the version upgrade. Upgrading the version to the latest stable version is great, but the best practice would be to create a separate PR to do that.

I will close this PR for now, and you are welcome to create an new one by following the best practices.

**Pull request closed without merging**
